#NEW IMPL

In [1]:
import pandas as pd

In [3]:
import pandas as pd

# URL of the CSV file
url = "./data/audit.csv"
# Read the CSV into a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
df.head()

,_id,supplier_name,public_water_system_id,reporting_month,county,hydrologic_region,climate_zone,total_population_served,reference_2014_population,county_under_drought_declaration,...,reported_preliminary_commercial_industrial_and_institutional_wa,reported_final_commercial_industrial_and_institutional_water,reported_recycled_water,reported_non_revenue_water,calculated_total_potable_water_production_gallons_ag_excluded,calculated_total_potable_water_production_gallons_2013_ag_exclu,calculated_commercial_agricultural_water_gallons,calculated_commercial_agricultural_water_gallons_2013,calculated_r_gpcd,qualification
0,1,East Bay Municipal Utilities District,CA0110005,2023-04-15T00:00:00,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,NaN,...,NaN,NaN,NaN,NaN,4.026000e+09,5.418000e+09,NaN,0.0,58.7125,1. To provide context…the average R-GPCD for A...
1,2,East Bay Municipal Utilities District,CA0110005,2023-03-15T00:00:00,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,739.0,NaN,NaN,NaN,3.672000e+09,4.928000e+09,NaN,0.0,47.7097,1. To provide context…the average R-GPCD for M...
2,3,East Bay Municipal Utilities District,CA0110005,2023-02-15T00:00:00,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,767.0,NaN,NaN,NaN,3.358000e+09,4.016000e+09,NaN,0.0,44.9732,1. To provide context…the average R-GPCD for F...
3,4,East Bay Municipal Utilities District,CA0110005,2023-01-15T00:00:00,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,939.0,NaN,NaN,NaN,3.696000e+09,4.099000e+09,NaN,0.0,48.0215,1. To provide context…the average R-GPCD for J...
4,5,East Bay Municipal Utilities District,CA0110005,2022-12-15T00:00:00,"Alameda,Contra Costa",San Francisco Bay,3,1430000,1379000,Yes,...,816.0,NaN,NaN,NaN,3.722000e+09,4.772000e+09,NaN,0.0,50.3767,1. To provide context…the average R-GPCD for D...

In [4]:
# Convert 'reporting_month' column to datetime
df['reporting_month'] = pd.to_datetime(df['reporting_month'])

# Create 'month_year' column in mm-yyyy format
df['month_year'] = df['reporting_month'].dt.strftime('%m-%Y')

# Display the modified DataFrame
df.head()

,_id,supplier_name,public_water_system_id,reporting_month,county,hydrologic_region,climate_zone,total_population_served,reference_2014_population,county_under_drought_declaration,...,reported_final_commercial_industrial_and_institutional_water,reported_recycled_water,reported_non_revenue_water,calculated_total_potable_water_production_gallons_ag_excluded,calculated_total_potable_water_production_gallons_2013_ag_exclu,calculated_commercial_agricultural_water_gallons,calculated_commercial_agricultural_water_gallons_2013,calculated_r_gpcd,qualification,month_year
0,1,East Bay Municipal Utilities District,CA0110005,2023-04-15,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,NaN,...,NaN,NaN,NaN,4.026000e+09,5.418000e+09,NaN,0.0,58.7125,1. To provide context…the average R-GPCD for A...,04-2023
1,2,East Bay Municipal Utilities District,CA0110005,2023-03-15,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,NaN,NaN,NaN,3.672000e+09,4.928000e+09,NaN,0.0,47.7097,1. To provide context…the average R-GPCD for M...,03-2023
2,3,East Bay Municipal Utilities District,CA0110005,2023-02-15,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,NaN,NaN,NaN,3.358000e+09,4.016000e+09,NaN,0.0,44.9732,1. To provide context…the average R-GPCD for F...,02-2023
3,4,East Bay Municipal Utilities District,CA0110005,2023-01-15,"Alameda,Contra Costa",San Francisco Bay,3,1440000,1379000,Yes,...,NaN,NaN,NaN,3.696000e+09,4.099000e+09,NaN,0.0,48.0215,1. To provide context…the average R-GPCD for J...,01-2023
4,5,East Bay Municipal Utilities District,CA0110005,2022-12-15,"Alameda,Contra Costa",San Francisco Bay,3,1430000,1379000,Yes,...,NaN,NaN,NaN,3.722000e+09,4.772000e+09,NaN,0.0,50.3767,1. To provide context…the average R-GPCD for D...,12-2022

In [5]:
import pandas as pd

# Assuming your CSV file is named 'reservoir_data.csv'
reservoir_df = pd.read_csv('./data/Reservoir_Monthly_Data.csv')

# Convert 'date' column to datetime
reservoir_df['DATE'] = pd.to_datetime(reservoir_df['DATE'])

# Extract month and year
reservoir_df['month_year'] = reservoir_df['DATE'].dt.strftime('%m-%Y')
reservoir_df.drop(['DATE'], axis=1, inplace=True)
reservoir_df.rename(columns={'STORAGE': 'reservoir_storage'}, inplace=True)
# Display the modified DataFrame
reservoir_df.head()

   reservoir_storage month_year
0          9247201.0    01-2014
1          8971363.0    01-2015
2          8790246.0    01-2016
3         16503134.0    01-2017
4         16297579.0    01-2018

In [6]:
# Merge the DataFrames on 'month_year'
merged_df = pd.merge(df, reservoir_df, on='month_year', how='left')

# Display the first few rows of the merged DataFrame
merged_df.head()
merged_df.columns

Index(['_id', 'supplier_name', 'public_water_system_id', 'reporting_month',
       'county', 'hydrologic_region', 'climate_zone',
       'total_population_served', 'reference_2014_population',
       'county_under_drought_declaration',
       'water_shortage_contingency_stage_invoked',
       'water_shortage_level_indicator',
       'dwr_state_standard_level_corresponding_to_stage',
       'water_production_units',
       'reported_preliminary_total_potable_water_production',
       'reported_final_total_potable_water_production',
       'preliminary_percent_residential_use', 'final_percent_residential_use',
       'reported_preliminary_commercial_agricultural_water',
       'reported_final_commercial_agricultural_water',
       'reported_preliminary_commercial_industrial_and_institutional_wa',
       'reported_final_commercial_industrial_and_institutional_water',
       'reported_recycled_water', 'reported_non_revenue_water',
       'calculated_total_potable_water_production_gallons_ag_excluded',
       'calculated_total_potable_water_production_gallons_2013_ag_exclu',
       'calculated_commercial_agricultural_water_gallons',
       'calculated_commercial_agricultural_water_gallons_2013',
       'calculated_r_gpcd', 'qualification', 'month_year',
       'reservoir_storage'],
      dtype='object')

In [7]:
ground_water=pd.read_csv('./data/i08_GroundwaterDepthSeasonal_Points.csv')
ground_water.columns

Index(['X', 'Y', 'OBJECTID', 'SITE_CODE', 'MSMT_DATE', 'EWM_STATION_ID',
       'WELL_NAME', 'SWN', 'WELL_USE', 'WLM_ORG_NAME', 'WSE', 'GSE_WSE', 'RPE',
       'GSE', 'MSMT_ISSUE', 'MSMT_YEAR', 'MSMT_SEASON', 'COMMENTS', 'SOURCE',
       'LAST_MODIFIED_DATE', 'MODIFIED_BY', 'DATE_DATA_REFERS_TO'],
      dtype='object')

In [10]:
# Convert 'date' column to datetime
ground_water['DATE_DATA_REFERS_TO'] = pd.to_datetime(ground_water['DATE_DATA_REFERS_TO'])

# Extract month and year
ground_water['month_year'] = ground_water['DATE_DATA_REFERS_TO'].dt.strftime('%m-%Y')
ground_water.drop(['DATE_DATA_REFERS_TO','OBJECTID','SITE_CODE','MSMT_DATE','SWN','SOURCE','MODIFIED_BY','EWM_STATION_ID','WELL_NAME'], axis=1, inplace=True)
ground_water.head()

KeyError: 'DATE_DATA_REFERS_TO'

In [9]:
combi_df = pd.merge(
    merged_df,
    ground_water,
    on='month_year',
    how='left'  # Keep all records from df1, add matching records from df2
)

KeyboardInterrupt: